<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useWorkflowStore } from '../stores/workflows'
import WorkflowCatalog from '../components/workflows/WorkflowCatalog.vue'
import WorkflowStageBuilder from '../components/workflows/WorkflowStageBuilder.vue'
import KanbanProjectionPreview from '../components/workflows/KanbanProjectionPreview.vue'
import BtnPrimary from '../components/common/BtnPrimary.vue'
import { GitFork, Plus, Trash2, Download, Check } from 'lucide-vue-next'

const workflowStore = useWorkflowStore()

const currentStages = ref<any[]>([])

onMounted(async () => {
  await workflowStore.fetchWorkflows()
  if (workflowStore.activeWorkflow) {
    currentStages.value = JSON.parse(JSON.stringify(workflowStore.activeWorkflow.stages))
  }
})

function onSelectWorkflow(id: string) {
  workflowStore.activeWorkflowId = id
  if (workflowStore.activeWorkflow) {
    currentStages.value = JSON.parse(JSON.stringify(workflowStore.activeWorkflow.stages))
  }
}

function addStage() {
  const num = currentStages.value.length + 1
  currentStages.value.push({
    id: `custom_stage_${num}`,
    name: `Custom Stage ${num}`,
    type: 'automated',
    assigned_role: 'developer',
    allowed_methods: ['BMAD'],
    write_lock_workspace: false,
    requires_gate: false,
  })
}

function removeStage(index: number) {
  currentStages.value.splice(index, 1)
}

const isExporting = ref(false)
const exportSuccess = ref(false)

function generateYaml(): string {
  const wf = workflowStore.activeWorkflow
  const name = wf ? wf.name : 'Custom SDLC Workflow'
  const id = wf ? wf.id : 'custom_workflow'
  const version = wf ? wf.version : '1.0.0'
  const desc = wf ? wf.description : 'Custom workflow generated by Meta-Orchestrator'

  let yaml = `# Meta-Orchestrator SDLC Pipeline Definition\n`
  yaml += `id: "${id}"\n`
  yaml += `name: "${name}"\n`
  yaml += `version: "${version}"\n`
  yaml += `description: "${desc}"\n`
  yaml += `stages:\n`

  for (const s of currentStages.value) {
    yaml += `  - id: "${s.id}"\n`
    yaml += `    name: "${s.name}"\n`
    yaml += `    type: "${s.type}"\n`
    yaml += `    assigned_role: "${s.assigned_role}"\n`
    yaml += `    allowed_methods:\n`
    for (const m of s.allowed_methods || []) {
      yaml += `      - "${m}"\n`
    }
    yaml += `    write_lock_workspace: ${Boolean(s.write_lock_workspace)}\n`
    yaml += `    requires_gate: ${Boolean(s.requires_gate)}\n`
    if (s.gate_criteria) {
      yaml += `    gate_criteria: "${s.gate_criteria}"\n`
    }
    if (s.required_artifacts && s.required_artifacts.length > 0) {
      yaml += `    required_artifacts:\n`
      for (const a of s.required_artifacts) {
        yaml += `      - "${a}"\n`
      }
    }
  }

  return yaml
}

async function exportYaml() {
  isExporting.value = true
  try {
    const yaml = generateYaml()
    const blob = new Blob([yaml], { type: 'text/yaml;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `${workflowStore.activeWorkflowId || 'workflow'}.yaml`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

    if (workflowStore.activeWorkflow) {
      await workflowStore.createWorkflow({
        ...workflowStore.activeWorkflow,
        stages: currentStages.value,
      })
    }
    exportSuccess.value = true
    setTimeout(() => {
      exportSuccess.value = false
    }, 2500)
  } catch (err) {
    console.error('Failed to export workflow YAML:', err)
  } finally {
    isExporting.value = false
  }
}
</script>

<template>
  <div class="h-full flex flex-col bg-slate-950 overflow-hidden">
    <!-- Header -->
    <div class="h-14 px-6 bg-slate-900/50 border-b border-slate-800 flex items-center justify-between">
      <div class="flex items-center gap-2">
        <GitFork class="w-4 h-4 text-emerald-400" />
        <h2 class="text-xs font-semibold text-slate-100 uppercase tracking-wide">
          Custom SDLC Workflow Builder & Manager
        </h2>
      </div>

      <div class="flex items-center gap-2">
        <div v-if="exportSuccess" class="flex items-center gap-1.5 text-xs text-emerald-400 px-2 py-1 bg-emerald-950/60 border border-emerald-800 rounded">
          <Check class="w-3.5 h-3.5" />
          <span>Exported & Saved</span>
        </div>
        <BtnPrimary :loading="isExporting" @click="exportYaml">
          <Download class="w-3.5 h-3.5" />
          <span>Export to .sdlc/workflow.yaml</span>
        </BtnPrimary>
      </div>
    </div>

    <!-- Content -->
    <main class="flex-1 p-6 overflow-y-auto space-y-6">
      <!-- 1. Catalog -->
      <WorkflowCatalog
        :workflows="workflowStore.workflows"
        :active-id="workflowStore.activeWorkflowId"
        @select="onSelectWorkflow"
      />

      <!-- 2. Live Kanban Projection Preview -->
      <KanbanProjectionPreview :stages="currentStages" />

      <!-- 3. Stage Sequence Builder -->
      <WorkflowStageBuilder
        :stages="currentStages"
        @add="addStage"
        @remove="removeStage"
        @update="currentStages = $event"
      />
    </main>
  </div>
</template>
