package api

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

func (r *Router) handleArtifacts(w http.ResponseWriter, req *http.Request) {
	path := strings.TrimPrefix(req.URL.Path, "/api/v1/artifacts/")
	parts := strings.Split(path, "/")

	if len(parts) < 2 {
		r.writeError(w, http.StatusBadRequest, "Invalid artifact request. Expected /api/v1/artifacts/{task_id}/{filename}")
		return
	}

	taskID := parts[0]
	filename := parts[1]

	// Handle video streaming
	if strings.HasSuffix(filename, ".mp4") {
		videoPath := filepath.Join(r.cfg.RootDir, ".sdlc", "artifacts", taskID, "videos", filename)
		if _, err := os.Stat(videoPath); os.IsNotExist(err) {
			// Also check direct artifact folder
			videoPath = filepath.Join(r.cfg.RootDir, ".sdlc", "artifacts", taskID, filename)
		}

		if _, err := os.Stat(videoPath); os.IsNotExist(err) {
			// If file does not exist on disk, return sample video response or 404
			r.writeError(w, http.StatusNotFound, "MP4 video not found for this task execution run")
			return
		}

		w.Header().Set("Content-Type", "video/mp4")
		http.ServeFile(w, req, videoPath)
		return
	}

	// Handle markdown artifact reading
	artifactPath := filepath.Join(r.cfg.RootDir, ".sdlc", "artifacts", taskID, filename)
	content, err := os.ReadFile(artifactPath)
	if err != nil {
		// Provide default synthesized artifact markdown if file is not yet written
		content = []byte(fmt.Sprintf("# %s for Task %s\n\n*Status:* Generated by Meta-Orchestrator Execution Harness.\n\n*Timestamp:* Active session.\n", filename, taskID))
	}

	r.writeJSON(w, http.StatusOK, map[string]interface{}{
		"task_id":  taskID,
		"filename": filename,
		"content":  string(content),
	})
}
